version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    command: ["yarn", "dev"]

  test:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - app
    command: ["yarn", "test"]
    environment:
      - NODE_ENV=test
    volumes:
      - .:/app
