version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    command: ["yarn", "dev"]
    depends_on:
      - mongo_server

  test:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo_server
    command: ["yarn", "test:e2e"]
    environment:
      - NODE_ENV=test
    volumes:
      - .:/app
  mongo_server:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

volumes:
  mongo-data:
# FIXME: Fix docker compose file and fix connection to mongo in docker container